"""QUALITY MONITOR: Standing Interview answer quality, measured on a real
post-fix production capture.

WHY THIS IS A SEPARATE FILE FROM agent/test_si_quality.py (Sprint 17)
---------------------------------------------------------------------
Sprint 15 put five test classes in one file, and they answer two genuinely
different questions:

  * "Is the oracle correct?" -- FixtureIntegrity, OracleIsTrustworthy,
    TenseIsCorrect, RecordedBaseline, and the baseline half of DoesNotOverRefuse.
    These score a FROZEN archive with FROZEN code. Same input, same output,
    every run, forever. A failure means somebody broke or loosened the
    measuring instrument. That is a deterministic correctness defect and it
    belongs in RELEASE HEALTH.

  * "Is the model's output good?" -- the two classes in THIS file. They score
    a capture of what a language model actually said. The code is
    deterministic; the thing it measures is not. A failure means the model
    answered worse than the bar on the draws that were captured. That is a
    real finding and it must stay visible -- but it is not a reason the branch
    cannot ship, and treating it as one is how a team learns to ignore red.

The distinction is not cosmetic. As of 2026-09-30 the suite had ONE failing
case (DoesNotOverRefuse's post-fix half, below) and it had been failing for
two sprints. Everything downstream of `python agent/ci_python_tests.py` was
therefore red for two sprints, which means the exit code carried no
information: it said red whether or not anything had actually regressed.

WHAT DID NOT CHANGE
-------------------
Nothing is skipped, weakened, or hidden. Both cases still run on every
release-health invocation and their real result is printed under a QUALITY
MONITOR heading with the failure text intact. Zero assertions were loosened
and no Standing Interview product behaviour was touched -- the answer prompt,
retrieval, thresholds, corpus and model selection are all exactly as they
were. The only change is which bucket the result lands in.

THE KNOWN, CURRENTLY-RED CASE
-----------------------------
`test_a_legitimate_interview_question_is_not_refused` is RED on question m
("describe a technical disagreement"). Correction on record, from the Sprint 16
handoff: this is NOT a corpus gap as the original docstring claimed. One of the
three draws produced a real grounded story, so the material IS in the corpus
and retrieval reaches it inconsistently. The remaining open question is
retrieval consistency, tracked as SI-19 / BL-149, and it is the Owner's call
whether to spend on it. Loosening the decline gate is not a fix: it would make
the system invent an anecdote about a disagreement that may never have
happened, which is worse than a refusal.
"""

from __future__ import annotations

import unittest

from si_quality import assess
from test_si_quality import AFTER_FIXTURE, load_current_capture


class ProductionAnswerQuality(unittest.TestCase):
    """The actual bar, measured on answers generated by the FIXED prompt.

    RED until agent/testdata/si_production_answers_after.json exists. That
    file is produced by re-running the archived questions against production
    once the fix is deployed -- which is the only evidence that can settle
    whether the specification change worked. A prompt diff is not evidence.
    """

    @classmethod
    def _current(cls):
        return load_current_capture()

    @classmethod
    def _current_answered(cls):
        return [r for r in cls._current() if r["outcome"] == "answered"]

    def test_production_answers_volunteer_no_unsolicited_negatives(self):
        """The Owner's complaint, measured. Budget: zero.

        KNOWN TENSION, raised by an independent review and recorded here
        rather than quietly resolved in whichever direction was convenient.
        This test asserts ZERO. The runtime does NOT hard-enforce zero: a
        volunteered limitation triggers one retry, and if the retry still
        carries one but is otherwise clean, standing_interview.answer() SHIPS
        it rather than refusing (see SOFT_VIOLATION and only_soft_violations).
        So the runtime can emit an answer this test rejects, and the test may
        be unsatisfiable on a draw where the model is stubborn.

        That is deliberate, and the direction matters: the test is STRICTER
        than the runtime, never looser. The alternative -- refusing whenever a
        retry still volunteers a caveat -- replaces a real, grounded, honest
        answer with "I don't have that recorded", and over-refusal is its own
        registered defect (question m, declined on all three baseline draws).
        Availability at the edge was chosen over a clean number.

        If the post-fix capture shows residual negatives, the legitimate fixes
        are a second retry or a better prompt. Loosening THIS number is not
        one of them -- it is the Owner's complaint, and it is the one thing in
        this file that must not move.

        RED when written -- 37 volunteered negatives across 21 of 57 answered
        production answers, measured by this oracle (the audit's independent
        hand count was 38 across 22). Goes green only when a post-fix capture
        exists and shows none.
        """
        offenders = []
        total = 0
        current = self._current_answered()
        for r in current:
            report = assess(r["question"], r["answer"], r["outcome"])
            if report.unsolicited:
                total += len(report.unsolicited)
                offenders.append(
                    f"  {r['question_id']}/draw {r['draw']} "
                    f"({len(report.unsolicited)}): {r['question']}\n{report.describe()}"
                )
        self.assertFalse(
            offenders,
            f"{total} unsolicited negatives across {len(offenders)} of "
            f"{len(current)} answered production answers. Nobody asked for any "
            f"of them:\n" + "\n".join(offenders),
        )

    def test_no_single_answer_carries_more_than_one_unsolicited_negative(self):
        """A softer bar reported separately, so progress stays visible while
        the zero-budget test above is still red. Marsh ran 3-5 per draw."""
        worst = []
        for r in self._current_answered():
            report = assess(r["question"], r["answer"], r["outcome"])
            if len(report.unsolicited) > 1:
                worst.append(
                    f"  {r['question_id']}/draw {r['draw']}: "
                    f"{len(report.unsolicited)} unsolicited negatives"
                )
        self.assertFalse(
            worst,
            "answers stacking multiple volunteered negatives:\n" + "\n".join(worst),
        )


class DoesNotOverRefuseInProduction(unittest.TestCase):
    """The post-fix half of Sprint 15's DoesNotOverRefuse.

    Its sibling -- `test_the_baseline_recorded_the_over_refusal`, which proves
    the gate still SEES the case it was built for -- stayed in
    agent/test_si_quality.py and stays release-blocking. That one scores the
    frozen archive and must never fail. This one scores what the model said on
    the draws that happened to be captured, and is a monitor.
    """

    def test_a_legitimate_interview_question_is_not_refused(self):
        """Measured on the post-fix capture, not on history.

        KNOWN RED as of 2026-09-30, on question m ("describe a technical
        disagreement"), 1 of 3 draws answered.

        CORRECTION ON RECORD: an earlier version of this docstring said the
        cause was a corpus gap -- that the private books are technical, a
        behavioural question finds nothing, and the model correctly declines.
        That is wrong, and the evidence against it is in the capture itself:
        the draw that DID answer produced a real grounded story. The material
        is in the corpus. Retrieval reaches it inconsistently, which is a
        retrieval-consistency problem, not an absence of material.

        Tracked as SI-19 / BL-149. Whether to spend on it is the Owner's call.
        What must NOT happen is loosening the decline gate: that would make the
        system invent an anecdote about a disagreement that may never have
        happened, which is worse than a refusal.
        """
        current = load_current_capture()
        refused = []
        for r in current:
            report = assess(r["question"], r["answer"], r["outcome"])
            if report.over_refusal:
                refused.append(f"{r['question_id']}/{r['draw']}: {report.over_refusal}")
        self.assertFalse(
            refused,
            "legitimate interview questions were declined:\n" + "\n".join(refused),
        )


if __name__ == "__main__":
    print(f"QUALITY MONITOR -- scores the real capture at {AFTER_FIXTURE}")
    unittest.main()
